name: char-contr-dev
channels:
- conda-forge
dependencies:
  - python>=3.10, <3.13
  - numpy>=1.26
  - pandas>=2.2
  - bokeh>=3.0
  - ipython
  - jupyter
  - ipykernel
  - matplotlib
  - behresp
  - openpyxl
  - pip
  - pip:
      - taxcalc
      - taxbrain
      - pypandoc
      - tabulate
      - xlrd
